### ISSUE TITLE
new Setup.sh is interfering with auto install script

### ISSUE THREAD

**Issue by kamach2024** [ARK-Electronics/ark_jetson_scripts#12]
we had headless install configured for the board, now the y/n questions are interfering with it. Can you add a parameter to give those answers pre-execution?

**Comment by AlexKlimaj** [comment]
Let me know if this helps.
https://github.com/ARK-Electronics/ark_companion_scripts/pull/13

**Comment by kamach2024** [comment]
will give it a try today and report it back, thanks for the fast reply!

**Comment by dakejahl** [comment]
```
-d, --install-dds-agent    Install micro-xrce-dds-agent
-l, --install-logloader    Install logloader
-e, --email EMAIL          Email to use for logloader
-u, --upload-to-flight-review  Auto upload logs to PX4 Flight Review
-p, --public-logs          Make logs public on PX4 Flight Review
```
example usage
```
./setup.sh -d -l -e dahl.jakejacob@gmail.com -u
```

**Comment by AlexKlimaj** [comment]
@kaangoksalmach did this take care of your issue?
