### ISSUE TITLE
Hostname change not working on Pi

### ISSUE THREAD

**Issue by AlexKlimaj** [ARK-Electronics/ark_jetson_scripts#25]
When I use the UI to change the hostname on a Pi, it doesn't take it even after a reboot. I was able to change the hostname manually through the command line and raspi-config.

**Comment by dakejahl** [comment]
Looks like debian requires root for hostnamectl but ubuntu doesn't. The way things work right now is that there isn't anything that requires root. I wasn't going to give any of the services sudo privileges, need to think about how to do this

**Comment by dakejahl** [comment]
Figured it out. I needed to give hostnamectl sudo privileges not the script which calls it
